CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id CHAR(36) NULL,
  event_type VARCHAR(100) NOT NULL,
  provider VARCHAR(50) NULL,
  ip_hash VARCHAR(64) NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB;
