CREATE TABLE IF NOT EXISTS sessions (
  id CHAR(64) NOT NULL PRIMARY KEY,
  user_id CHAR(36) NULL,
  data MEDIUMBLOB NOT NULL,
  last_access INT UNSIGNED NOT NULL,
  expires_at INT UNSIGNED NOT NULL
) ENGINE=InnoDB;
